import { Metadata } from "next";

export const metadata: Metadata = {
  title: "All Babysitters",
  description: "Generated by create next app",
};

const AllBabySitter = () => {
  return <div>ALl Babysitters</div>;
};

export default AllBabySitter;
